services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ../:/app
    depends_on:
      - vllm

  vllm:
    build:
      context: ..
      dockerfile: docker/Dockerfile.vllm
    ports:
      - "8001:8001"
    volumes:
      - ../:/app
    shm_size: '2gb'
